#!/bin/bash

function check_exist() {
	if [ -e $1 ]
	then
		read -p "'$1' already exists, remove? " -n 1 -r
		echo
		if [[ $REPLY =~ ^[Yy]$ ]]
		then
			rm $1
		else
			exit 1
		fi
	fi
}

function prompt_deletion() {
	read -p "Delete file: $1? " -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		rm -rf $1
		echo "File $1 deleted"
	fi
}

function encrypt_dir() {
	local base=$(basename $1)

	local zip_name="$base.zip"
	check_exist $zip_name

	local enc_name="$base.enc"
	check_exist $enc_name

	echo "Compressing..." && \
		zip -rv9 $zip_name $1 && \
		echo "Encrypting..." && \
		openssl enc -aes-256-cbc -md sha512-256 -salt -v -pbkdf2 -in $zip_name -out $enc_name && \
		echo "Removing $zip_name..." && \
		rm $zip_name && \
		echo "Successfully encrypted: $enc_name" && \
		prompt_deletion $1
}

function decrypt_dir() {
	local base=$(basename $1)
	local zip_name="${base%.*}.zip"
	check_exist $zip_name

	echo "Decrypting..." && \
		openssl enc -d -aes-256-cbc -md sha512-256 -salt -v -pbkdf2 -in $1 -out $zip_name && \
		echo "Extracting from $zip_name..." && \
		unzip $zip_name && \
		rm $zip_name
}

if [ -z ${1+x} ] || [ -z ${2+x} ]; then
	echo "Usage: vault <enc|dec> <file>"
	exit 1
fi;

case "$1" in
	enc) encrypt_dir $2
		 ;;
	dec) decrypt_dir $2
		 ;;
esac
