#!/bin/bash

function check_exist() {
	if [ -e $1 ]
	then
		read -p "'$1' already exists, remove? " -n 1 -r
		echo
		if [[ $REPLY =~ ^[Yy]$ ]]
		then
			rm $1
		else
			exit 1
		fi
	fi
}

function prompt_deletion() {
	read -p "Delete file: $1? " -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		rm -rf $1
		echo "File $1 deleted"
	fi
}

function encrypt_dir() {
	local enc_name="$(basename $1).enc"
	check_exist $enc_name

	echo "Compressing and encrypting $1 -> $enc_name..." && \
		tar -cf - $1 | gpg --cipher-algo AES256 -co $enc_name && \
		echo "Successfully encrypted: $enc_name" && \
		prompt_deletion $1
}

function decrypt_dir() {
	local base=$(basename $1)
	local dest="${base%.*}"
	check_exist $dest
	echo "Decrypting and decompressing $1 -> $dest..." && gpg -d $1 | tar -x
}

if [ -z ${1+x} ] || [ -z ${2+x} ]; then
	echo "Usage: vault <enc|dec> <file>"
	exit 1
fi;

case "$1" in
	enc) encrypt_dir $2
		 ;;
	dec) decrypt_dir $2
		 ;;
esac
