# Basic environment
export LC_ALL=en_GB.UTF-8
export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

# Favourite editor
export EDITOR=emacs

# Go environment
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"

# if homebrew is installed include its binaries
function init_brew() {
	local brewprefix=""

	if [ -f "/usr/local/bin/brew" ]; then
		 brewprefix=$(/usr/local/bin/brew --prefix);
	fi

	if [ -f "/opt/homebrew/bin/brew" ]; then
		 brewprefix=$(/opt/homebrew/bin/brew --prefix);
	fi

	if [ $brewprefix ]; then
		 export PATH="$brewprefix/bin:$brewprefix/sbin:$PATH";
		 FPATH="$brewprefix/share/zsh/site-functions:$FPATH";
	fi
}
init_brew
unfunction init_brew

# Load user environment
if [ -f ~/.zshenv.local ]; then
	source ~/.zshenv.local;
fi

# Custom scripts
if [ -d ~/.scripts ]; then
	export PATH="$HOME/.scripts:$PATH";
fi
