# Basic environment
export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8
export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

# Options
setopt prompt_subst

# Aliases
alias emacs='emacsclient -c --socket-name=emacs-daemon'
alias ll='ls -alF'

# Version control prompt status configuration
autoload -Uz add-zsh-hook
add-zsh-hook precmd vcs_info
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' use-prompt-escapes true
zstyle ':vcs_info:*' stagedstr '%F{yellow}|s%f'
zstyle ':vcs_info:*' unstagedstr '%F{yellow}|u%f'
zstyle ':vcs_info:*' formats       '%K{white}%F{black}@%b%f%k%u%c'
zstyle ':vcs_info:*' actionformats '%K{white}%F{black}@%b>%a%f%k%u%c'

# reset the prompt
PROMPT=""
# indicate SSH connection
if [[ "${SSH_TTY}" ]]; then
		PROMPT+='%B%F{yellow}ssh://%f%b'
fi;
# username and hostname
PROMPT+='%B%F{magenta}%n@%M%f%b'
# working directory
PROMPT+='%F{white}:%~%f'
# # git branch and status flags
PROMPT+='${vcs_info_msg_0_}'
# amount of running background jobs on the machine
PROMPT+='%(1j. [%j].)'
# red if the last exit code was non-zero
PROMPT+=' %(?.%F{green}.%F{red})%#%f '

# Load user environment
if [ -f ~/.user_env ]; then
	source ~/.user_env
fi

# Load aliases
if [ -f ~/.aliases ]; then
	source ~/.aliases
fi
